# Generated by Django 4.2.11 on 2024-06-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepair",
            name="judge",
            field=models.BooleanField(default=False, verbose_name="是否为同义句"),
        ),
    ]
