# Generated by Django 4.2.11 on 2024-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("show", "0002_sentencepair_judge"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentencepair",
            name="context1_schema",
            field=models.CharField(default="", max_length=200, verbose_name="句子1图式"),
        ),
        migrations.AddField(
            model_name="sentencepair",
            name="context2_schema",
            field=models.CharField(default="", max_length=200, verbose_name="句子2图式"),
        ),
    ]
