# Generated by Django 4.2.11 on 2024-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spatialquery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="spaceinfo",
            name="pattern",
            field=models.CharField(default="", max_length=200),
        ),
    ]
